### ISSUE TITLE
Got some error when execute the python script

### ISSUE THREAD

**Issue by bukharidxb** [nebelschwaden/fuckoo#1]
I got the below error when executing the script. Please check where I am doing mistakes.

Processing: jsontestfiles\data\1.json
fuckoo.py:12: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  df_dataset = pd.concat([df_dataset,pd.DataFrame(pd.Series(values),columns=[name])],axis=1)
Processing: jsontestfiles\data\13.json
Processing: jsontestfiles\data\15.json
Processing: jsontestfiles\data\17.json
Processing: jsontestfiles\data\18.json
Processing: jsontestfiles\data\2.json
Traceback (most recent call last):
  File "fuckoo.py", line 146, in <module>
    filter(sys.argv[1], sys.argv[2])
  File "fuckoo.py", line 138, in filter
    general.to_csv(result_path, index=False)
  File "C:\Users\DXB\anaconda3\lib\site-packages\pandas\core\generic.py", line 3170, in to_csv
    formatter.save()
  File "C:\Users\DXB\anaconda3\lib\site-packages\pandas\io\formats\csvs.py", line 185, in save
    f, handles = get_handle(
  File "C:\Users\DXB\anaconda3\lib\site-packages\pandas\io\common.py", line 493, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, errors=errors, newline="")
FileNotFoundError: [Errno 2] No such file or directory: './raw/data.csv'

**Comment by nebelschwaden** [comment]
Hello @bukharidxb, thanks for reporting! 
This issue was caused because the script wanted to save the dataset in the "raw" folder which didn't exist. The script has been modified to save the dataset in the current directory from where the script has been executed.

**Comment by bukharidxb** [comment]
Thank you for a prompt action. I can see there is no error now. How can we add the labels information (malware/benign)?

Thank you

**Comment by nebelschwaden** [comment]
Currently, the script cannot add the label since a JSON file generated by Cuckoo does not contain information that describes an artifact as malware, etc. though I'm working on an enhanced version of this script that will add the labels and will be released in the future!
